# Generated by Django 5.1.2 on 2025-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_campaign_creator_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='creator_username',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='probem_statement',
            new_name='problem_statement',
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
