# Generated by Django 5.1.2 on 2025-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_creator_username_campaign_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='achieved_funding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
