# Generated by Django 5.1.2 on 2025-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_campaign_achieved_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_pledges',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
