# Generated by Django 5.1.2 on 2025-04-23 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('projects', '0005_campaign_total_pledges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('pledge_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_pledged', models.DateTimeField(default=django.utils.timezone.now)),
                ('backer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges_made', to='accounts.pledgepool_user')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges_received', to='accounts.pledgepool_user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.campaign')),
            ],
        ),
    ]
