# Generated by Django 5.1.2 on 2025-05-28 10:41

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_gallery',
        ),
        migrations.CreateModel(
            name='CampaignGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.models.upload_gallery)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projects.campaign')),
            ],
        ),
    ]
