# Generated by Django 5.1.2 on 2025-03-27 07:30

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pledgepool_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to_pfps)),
                ('description', models.TextField()),
            ],
        ),
    ]
