# Generated by Django 5.1.2 on 2025-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pledgepool_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgepool_user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pledgepool_user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
