# Generated by Django 5.1.2 on 2025-03-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pledgepool_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgepool_user',
            name='languages',
        ),
    ]
